# Web Scraping Using Python: Complete Structured Guide
    1. Introduction to Web Scraping
        What is Web Scraping?
            Web scraping is the automated process of extracting data from websites using programming instead of manual copy-paste.
    
        Why Web Scraping is Used
            Market research
            Price monitoring
            Job aggregation
            News analysis
            Dataset creation for ML

# 2. How Web Scraping Works (Pipeline)

    Explain this flow clearly to students:
    
        Send HTTP request
        Receive HTML response
        Parse HTML
        Extract required elements
        Clean data
        Store data (CSV / DataFrame / Database)
        You can draw this pipeline on the board.

# 3. Required Python Libraries
    Core Libraries
        Library	               Purpose
        requests	           Fetch webpage
        BeautifulSoup	       Parse HTML
        lxml	               Fast parser
        pandas	               Create DataFrame
        pymysql/sqlite3	       Store in database
        selenium	           Dynamic websites

In [28]:
pip install requests

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: requests in e:\anaconda\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\anaconda\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in e:\anaconda\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\anaconda\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in e:\anaconda\lib\site-packages (from requests) (2025.4.26)

In [29]:
pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in e:\anaconda\lib\site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in e:\anaconda\lib\site-packages (from beautifulsoup4) (2.5)
Note: you may need to restart the kernel to use updated packages.

In [30]:
pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in e:\anaconda\lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [31]:
pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\dmin\appdata\roaming\python\python313\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import requests
url = "https://quotes.toscrape.com"
response = requests.get(url)
print(response.status_code) #[200 -> sucess, 404 -> Not found, 403 -> forbidden, 500 -> server error]

200

In [3]:
url2 = "https://en.wikipedia.org/wiki/World_population"
response2 = requests.get(url2)
print(response2.status_code)

403

In [4]:
print(response.text)

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes to Scrape</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/main.css">


</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>

                    <a href="/login">Login</a>

                </p>
            </div>
        </div>


<div class="row">
    <div class="col-md-8">

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
        <span>by <small class="author" itemprop="author">Albert Einstein</small>
        <a href="/author/Albert-Einstein">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world" /    >

            <a class="tag" href="/tag/change/page/1/">change</a>

            <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>

            <a class="tag" href="/tag/thinking/page/1/">thinking</a>

            <a class="tag" href="/tag/world/page/1/">world</a>

        </div>
    </div>

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
        <span>by <small class="author" itemprop="author">J.K. Rowling</small>
        <a href="/author/J-K-Rowling">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="abilities,choices" /    >

            <a class="tag" href="/tag/abilities/page/1/">abilities</a>

            <a class="tag" href="/tag/choices/page/1/">choices</a>

        </div>
    </div>

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
        <span>by <small class="author" itemprop="author">Albert Einstein</small>
        <a href="/author/Albert-Einstein">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="inspirational,life,live,miracle,miracles" /    >

            <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>

            <a class="tag" href="/tag/life/page/1/">life</a>

            <a class="tag" href="/tag/live/page/1/">live</a>

            <a class="tag" href="/tag/miracle/page/1/">miracle</a>

            <a class="tag" href="/tag/miracles/page/1/">miracles</a>

        </div>
    </div>

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>
        <span>by <small class="author" itemprop="author">Jane Austen</small>
        <a href="/author/Jane-Austen">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="aliteracy,books,classic,humor" /    >

            <a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>

            <a class="tag" href="/tag/books/page/1/">books</a>

            <a class="tag" href="/tag/classic/page/1/">classic</a>

            <a class="tag" href="/tag/humor/page/1/">humor</a>

        </div>
    </div>

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it&#39;s better to be absolutely ridiculous than absolutely boring.”</span>
        <span>by <small class="author" itemprop="author">Marilyn Monroe</small>
        <a href="/author/Marilyn-Monroe">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="be-yourself,inspirational" /    >

            <a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>

            <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>

        </div>
    </div>

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>
        <span>by <small class="author" itemprop="author">Albert Einstein</small>
        <a href="/author/Albert-Einstein">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="adulthood,success,value" /    >

            <a class="tag" href="/tag/adulthood/page/1/">adulthood</a>

            <a class="tag" href="/tag/success/page/1/">success</a>

            <a class="tag" href="/tag/value/page/1/">value</a>

        </div>
    </div>

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>
        <span>by <small class="author" itemprop="author">André Gide</small>
        <a href="/author/Andre-Gide">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="life,love" /    >

            <a class="tag" href="/tag/life/page/1/">life</a>

            <a class="tag" href="/tag/love/page/1/">love</a>

        </div>
    </div>

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“I have not failed. I&#39;ve just found 10,000 ways that won&#39;t work.”</span>
        <span>by <small class="author" itemprop="author">Thomas A. Edison</small>
        <a href="/author/Thomas-A-Edison">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="edison,failure,inspirational,paraphrased" /    >

            <a class="tag" href="/tag/edison/page/1/">edison</a>

            <a class="tag" href="/tag/failure/page/1/">failure</a>

            <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>

            <a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>

        </div>
    </div>

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it&#39;s in hot water.”</span>
        <span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>
        <a href="/author/Eleanor-Roosevelt">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="misattributed-eleanor-roosevelt" /    >

            <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>

        </div>
    </div>

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
        <span>by <small class="author" itemprop="author">Steve Martin</small>
        <a href="/author/Steve-Martin">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="humor,obvious,simile" /    >

            <a class="tag" href="/tag/humor/page/1/">humor</a>

            <a class="tag" href="/tag/obvious/page/1/">obvious</a>

            <a class="tag" href="/tag/simile/page/1/">simile</a>

        </div>
    </div>

    <nav>
        <ul class="pager">


            <li class="next">
                <a href="/page/2/">Next <span aria-hidden="true">&rarr;</span></a>
            </li>

        </ul>
    </nav>
    </div>
    <div class="col-md-4 tags-box">

            <h2>Top Ten tags</h2>

            <span class="tag-item">
            <a class="tag" style="font-size: 28px" href="/tag/love/">love</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 26px" href="/tag/inspirational/">inspirational</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 26px" href="/tag/life/">life</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 24px" href="/tag/humor/">humor</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 22px" href="/tag/books/">books</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 14px" href="/tag/reading/">reading</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 10px" href="/tag/friendship/">friendship</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 8px" href="/tag/friends/">friends</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 8px" href="/tag/truth/">truth</a>
            </span>

            <span class="tag-item">
            <a class="tag" style="font-size: 6px" href="/tag/simile/">simile</a>
            </span>


    </div>
</div>

    </div>
    <footer class="footer">
        <div class="container">
            <p class="text-muted">
                Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
            </p>
            <p class="copyright">
                Made with <span class='zyte'>❤</span> by <a class='zyte' href="https://www.zyte.com">Zyte</a>
            </p>
        </div>
    </footer>
</body>
</html>

# Explain Status Codes
    Code	Meaning
    200	    Success
    403	    Forbidden
    404	    Not found
    500	    Server error

# Handling Headers (Important)

    Some websites block bots.
    headers = {
        "User-Agent": "Mozilla/5.0"
    }
    response = requests.get(url, headers=headers)

In [ ]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, "lxml")
print(soup.title)
print(soup.title.text)
print(soup.text)

<title>Quotes to Scrape</title>
Quotes to Scrape



Quotes to Scrape








Quotes to Scrape




Login






“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
by Albert Einstein
(about)


            Tags:

change
deep-thoughts
thinking
world



“It is our choices, Harry, that show what we truly are, far more than our abilities.”
by J.K. Rowling
(about)


            Tags:

abilities
choices



“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
by Albert Einstein
(about)


            Tags:

inspirational
life
live
miracle
miracles



“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
by Jane Austen
(about)


            Tags:

aliteracy
books
classic
humor



“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
by Marilyn Monroe
(about)


            Tags:

be-yourself
inspirational



“Try not to become a man of success. Rather become a man of value.”
by Albert Einstein
(about)


            Tags:

adulthood
success
value



“It is better to be hated for what you are than to be loved for what you are not.”
by André Gide
(about)


            Tags:

life
love



“I have not failed. I've just found 10,000 ways that won't work.”
by Thomas A. Edison
(about)


            Tags:

edison
failure
inspirational
paraphrased



“A woman is like a tea bag; you never know how strong it is until it's in hot water.”
by Eleanor Roosevelt
(about)


            Tags:

misattributed-eleanor-roosevelt



“A day without sunshine is like, you know, night.”
by Steve Martin
(about)


            Tags:

humor
obvious
simile





Next →





Top Ten tags

love


inspirational


life


humor


books


reading


friendship


friends


truth


simile







                Quotes by: GoodReads.com


                Made with ❤ by Zyte

# Important Methods

In [10]:
heading1 = soup.find("h1")
print(heading1)
print(":"*50)
par = soup.find('p')
print(par)

<h1>
<a href="/" style="text-decoration: none">Quotes to Scrape</a>
</h1>
::::::::::::::::::::::::::::::::::::::::::::::::::
<p>
<a href="/login">Login</a>
</p>

In [11]:
soup.find_all("span", class_="text")

[<span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>,
 <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>,
 <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>,
 <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>,
 <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>,
 <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>,
 <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>,
 <span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>,
 <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>,
 <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>]

In [13]:
# tag.text
heading1.text

'\nQuotes to Scrape\n'

In [15]:
url = "https://quotes.toscrape.com"
response = requests.get(url)

soup = BeautifulSoup(response.text, "lxml")

quotes = soup.find_all("span", class_="text")
authors = soup.find_all("small", class_="author")
# print(":"*20)
# print(quotes)
# print(authors)
# print(":"*20)
quote_list = []
author_list = []

for i in range(len(quotes)):
    quote_list.append(quotes[i].text)
    author_list.append(authors[i].text)

print(quote_list[:3])
print(author_list[:3])

['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”', '“It is our choices, Harry, that show what we truly are, far more than our abilities.”', '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”']
['Albert Einstein', 'J.K. Rowling', 'Albert Einstein']

# 7. Step 4 — Data Cleaning (Important Teaching Part)
    Common cleaning steps:
        Remove extra spaces
        Remove newline characters
        Handle missing values
        Convert data types
    Example:
    clean_quotes = [q.strip() for q in quote_list]

In [16]:
clean_quot_loop = []
for i in quote_list:
    clean_quot_loop.append(i.strip())
clean_quot_loop

['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”',
 '“It is our choices, Harry, that show what we truly are, far more than our abilities.”',
 '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”',
 '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”',
 "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”",
 '“Try not to become a man of success. Rather become a man of value.”',
 '“It is better to be hated for what you are than to be loved for what you are not.”',
 "“I have not failed. I've just found 10,000 ways that won't work.”",
 "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”",
 '“A day without sunshine is like, you know, night.”']

In [17]:
clean_author_loop = []
for i in author_list:
    clean_author_loop.append(i.strip())
clean_author_loop

['Albert Einstein',
 'J.K. Rowling',
 'Albert Einstein',
 'Jane Austen',
 'Marilyn Monroe',
 'Albert Einstein',
 'André Gide',
 'Thomas A. Edison',
 'Eleanor Roosevelt',
 'Steve Martin']

In [18]:
clean_quotes = [q.strip() for q in quote_list]
clean_author = [au.strip() for au in author_list]
print(":"*50)
print(clean_quotes)
print(":"*50)
print(clean_author)

::::::::::::::::::::::::::::::::::::::::::::::::::
['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”', '“It is our choices, Harry, that show what we truly are, far more than our abilities.”', '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”', '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”", '“Try not to become a man of success. Rather become a man of value.”', '“It is better to be hated for what you are than to be loved for what you are not.”', "“I have not failed. I've just found 10,000 ways that won't work.”", "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”", '“A day without sunshine is like, you know, night.”']
::::::::::::::::::::::::::::::::::::::::::::::::::
['Albert Einstein', 'J.K. Rowling', 'Albert Einstein', 'Jane Austen', 'Marilyn Monroe', 'Albert Einstein', 'André Gide', 'Thomas A. Edison', 'Eleanor Roosevelt', 'Steve Martin']

In [19]:
import pandas as pd
data = {
    "Quote": clean_quotes,
    "Author": clean_author
}
print(":")
print(data)
print(":"*50)
df = pd.DataFrame(data)
display(df)

:
{'Quote': ['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”', '“It is our choices, Harry, that show what we truly are, far more than our abilities.”', '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”', '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”", '“Try not to become a man of success. Rather become a man of value.”', '“It is better to be hated for what you are than to be loved for what you are not.”', "“I have not failed. I've just found 10,000 ways that won't work.”", "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”", '“A day without sunshine is like, you know, night.”'], 'Author': ['Albert Einstein', 'J.K. Rowling', 'Albert Einstein', 'Jane Austen', 'Marilyn Monroe', 'Albert Einstein', 'André Gide', 'Thomas A. Edison', 'Eleanor Roosevelt', 'Steve Martin']}
::::::::::::::::::::::::::::::::::::::::::::::::::

                                               Quote             Author
0  “The world as we have created it is a process ...    Albert Einstein
1  “It is our choices, Harry, that show what we t...       J.K. Rowling
2  “There are only two ways to live your life. On...    Albert Einstein
3  “The person, be it gentleman or lady, who has ...        Jane Austen
4  “Imperfection is beauty, madness is genius and...     Marilyn Monroe
5  “Try not to become a man of success. Rather be...    Albert Einstein
6  “It is better to be hated for what you are tha...         André Gide
7  “I have not failed. I've just found 10,000 way...   Thomas A. Edison
8  “A woman is like a tea bag; you never know how...  Eleanor Roosevelt
9  “A day without sunshine is like, you know, nig...       Steve Martin

In [44]:
data = {
    "Quote": clean_quot_loop,
    "Author": clean_author_loop
}
print(":")
print(data)
print(":"*50)
df = pd.DataFrame(data)
display(df)

:
{'Quote': ['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”', '“It is our choices, Harry, that show what we truly are, far more than our abilities.”', '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”', '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”", '“Try not to become a man of success. Rather become a man of value.”', '“It is better to be hated for what you are than to be loved for what you are not.”', "“I have not failed. I've just found 10,000 ways that won't work.”", "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”", '“A day without sunshine is like, you know, night.”'], 'Author': ['Albert Einstein', 'J.K. Rowling', 'Albert Einstein', 'Jane Austen', 'Marilyn Monroe', 'Albert Einstein', 'André Gide', 'Thomas A. Edison', 'Eleanor Roosevelt', 'Steve Martin']}
::::::::::::::::::::::::::::::::::::::::::::::::::

                                               Quote             Author
0  “The world as we have created it is a process ...    Albert Einstein
1  “It is our choices, Harry, that show what we t...       J.K. Rowling
2  “There are only two ways to live your life. On...    Albert Einstein
3  “The person, be it gentleman or lady, who has ...        Jane Austen
4  “Imperfection is beauty, madness is genius and...     Marilyn Monroe
5  “Try not to become a man of success. Rather be...    Albert Einstein
6  “It is better to be hated for what you are tha...         André Gide
7  “I have not failed. I've just found 10,000 way...   Thomas A. Edison
8  “A woman is like a tea bag; you never know how...  Eleanor Roosevelt
9  “A day without sunshine is like, you know, nig...       Steve Martin

In [47]:
m_q = len( quote_list[0] )
m_a = len( author_list[0] )
m_qu = quote_list[0] 
m_au = author_list[0]

for i in range(len(quote_list)):
    if len(quote_list[i]) > m_q:
        m_q = len(quote_list[i])
        m_qu = quote_list[i]
        
    if len(author_list[i]) > m_a:
        m_a = len(author_list[i])
        m_au = author_list[i]

print(":"*50)
print("Max length of Qu: ", m_q, m_qu)
print("Max length of au: ", m_a, m_au)
print(":"*50)

Max length of Qu:  131 “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
Max length of au:  17 Eleanor Roosevelt

In [20]:
import pymysql as myc
conn = myc.connect(
    host = 'localhost',
    user = 'root',
    password = 'Akash@121',
    database = 'scrapping_db'
)
print("connected: ",conn)
cur = conn.cursor()

connected:  <pymysql.connections.Connection object at 0x000001B783E3A270>

In [21]:
cur.execute("""
    create table if not exists
    quotes_tb (
        id int auto_increment primary key,
        quote text,
        author varchar(20)
    )
""")
print("Table created!!")

Table created!!

In [22]:
for index, row in df.iterrows():
    print("processing for ", index)
    cur.execute(
        "insert into quotes_tb (quote, author) values (%s, %s)" , 
        (row['Quote'], row['Author'])
    )
    print(":"*50)
    
conn.commit()
print("Data inserted")

processing for  0
::::::::::::::::::::::::::::::::::::::::::::::::::
processing for  1
::::::::::::::::::::::::::::::::::::::::::::::::::
processing for  2
::::::::::::::::::::::::::::::::::::::::::::::::::
processing for  3
::::::::::::::::::::::::::::::::::::::::::::::::::
processing for  4
::::::::::::::::::::::::::::::::::::::::::::::::::
processing for  5
::::::::::::::::::::::::::::::::::::::::::::::::::
processing for  6
::::::::::::::::::::::::::::::::::::::::::::::::::
processing for  7
::::::::::::::::::::::::::::::::::::::::::::::::::
processing for  8
::::::::::::::::::::::::::::::::::::::::::::::::::
processing for  9
::::::::::::::::::::::::::::::::::::::::::::::::::
Data inserted

In [23]:
cur.execute("select * from quotes_tb")
rows = cur.fetchall()
for r in rows:
    print(r)

(1, '“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”', 'Albert Einstein')
(2, '“It is our choices, Harry, that show what we truly are, far more than our abilities.”', 'J.K. Rowling')
(3, '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”', 'Albert Einstein')
(4, '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', 'Jane Austen')
(5, "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”", 'Marilyn Monroe')
(6, '“Try not to become a man of success. Rather become a man of value.”', 'Albert Einstein')
(7, '“It is better to be hated for what you are than to be loved for what you are not.”', 'André Gide')
(8, "“I have not failed. I've just found 10,000 ways that won't work.”", 'Thomas A. Edison')
(9, "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”", 'Eleanor Roosevelt')
(10, '“A day without sunshine is like, you know, night.”', 'Steve Martin')

In [24]:
cur.close()
conn.close()